version: '3'

volumes:
  db-data:
    driver: local
  minio-data:
    driver: local

networks:
  keycloak-network:

services:
  postgres:
    image: 'postgres:16'
    container_name: 'inventory-postgres'
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    image: keycloak/keycloak:26.0
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - keycloak-network
      -
  minio:
    image: minio/minio:latest
    container_name: 'tasklist-minio'
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_ACCESS_KEY}
    ports:
      - "9090:9090"
      - "9000:9000"
    volumes:
      - minio-data:/minio
    command: server ~/minio --console-address :9090