spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: prod

server:
  port: 8081

minio:
  bucket: ${MINIO_BUCKET}
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}

secret:
  jwt: ${JWT_SECRET}

jwt:
  auth:
    converter:
      resource-id: inventory-client
      principle-attribute: preferred_username